### ISSUE TITLE
Examples about using

### ISSUE THREAD

**Issue by nikita-sheremet-java-developer** [FelixEngl/KotlinUsings#1]
Not all programers are familiar with C# :)

Could you please add just a couple examples? For example - how it was before and how it is now with your library.

Thanks.

**Comment by BoxResin** [comment]
@nikita-sheremet-java-developer 

I think the usage may be:
```kotlin
val a: Closeable = TODO()
val b: Closeable = TODO()
val c: Closeable = TODO()

using(a, b, c) { a, b, c ->
    // TODO
}
```
